export interface City {
  name: string;
  country: string;
  countryCode: string;
}

// This is a comprehensive dataset tailored for an app targeting Iranian users.
// It includes top travel/diaspora hubs, major world cities, and all Iranian cities with airports.
export const cityData: City[] = [
  // == Iranian Diaspora & Popular Travel Hubs ==
  { name: "Los Angeles", country: "USA", countryCode: "US" },
  { name: "Irvine", country: "USA", countryCode: "US" },
  { name: "Glendale", country: "USA", countryCode: "US" },
  { name: "Beverly Hills", country: "USA", countryCode: "US" },
  { name: "Toronto", country: "Canada", countryCode: "CA" },
  { name: "Vancouver", country: "Canada", countryCode: "CA" },
  { name: "Montreal", country: "Canada", countryCode: "CA" },
  { name: "Richmond Hill", country: "Canada", countryCode: "CA" },
  { name: "North Vancouver", country: "Canada", countryCode: "CA" },
  { name: "London", country: "United Kingdom", countryCode: "GB" },
  { name: "Manchester", country: "United Kingdom", countryCode: "GB" },
  { name: "Glasgow", country: "United Kingdom", countryCode: "GB" },
  { name: "Stockholm", country: "Sweden", countryCode: "SE" },
  { name: "Gothenburg", country: "Sweden", countryCode: "SE" },
  { name: "Malmö", country: "Sweden", countryCode: "SE" },
  { name: "Hamburg", country: "Germany", countryCode: "DE" },
  { name: "Berlin", country: "Germany", countryCode: "DE" },
  { name: "Frankfurt", country: "Germany", countryCode: "DE" },
  { name: "Cologne", country: "Germany", countryCode: "DE" },
  { name: "Düsseldorf", country: "Germany", countryCode: "DE" },
  { name: "Munich", country: "Germany", countryCode: "DE" },
  { name: "Paris", country: "France", countryCode: "FR" },
  { name: "Istanbul", country: "Turkey", countryCode: "TR" },
  { name: "Antalya", country: "Turkey", countryCode: "TR" },
  { name: "Ankara", country: "Turkey", countryCode: "TR" },
  { name: "Izmir", country: "Turkey", countryCode: "TR" },
  { name: "Dubai", country: "United Arab Emirates", countryCode: "AE" },
  { name: "Yerevan", country: "Armenia", countryCode: "AM" },
  { name: "Tbilisi", country: "Georgia", countryCode: "GE" },
  { name: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
  { name: "Bangkok", country: "Thailand", countryCode: "TH" },
  { name: "Sydney", country: "Australia", countryCode: "AU" },
  { name: "Melbourne", country: "Australia", countryCode: "AU" },
  { name: "Perth", country: "Australia", countryCode: "AU" },
  { name: "Brisbane", country: "Australia", countryCode: "AU" },
  { name: "Adelaide", country: "Australia", countryCode: "AU" },
  { name: "Najaf", country: "Iraq", countryCode: "IQ" },
  { name: "Karbala", country: "Iraq", countryCode: "IQ" },
  { name: "Baku", country: "Azerbaijan", countryCode: "AZ" },
  { name: "Vienna", country: "Austria", countryCode: "AT" },
  { name: "Oslo", country: "Norway", countryCode: "NO" },
  { name: "Copenhagen", country: "Denmark", countryCode: "DK" },
  { name: "Amsterdam", country: "Netherlands", countryCode: "NL" },

  // == Major Iranian Cities (with Airports) ==
  { name: "Tehran", country: "Iran", countryCode: "IR" },
  { name: "Mashhad", country: "Iran", countryCode: "IR" },
  { name: "Isfahan", country: "Iran", countryCode: "IR" },
  { name: "Shiraz", country: "Iran", countryCode: "IR" },
  { name: "Tabriz", country: "Iran", countryCode: "IR" },
  { name: "Kish Island", country: "Iran", countryCode: "IR" },
  { name: "Qeshm Island", country: "Iran", countryCode: "IR" },
  { name: "Ahvaz", country: "Iran", countryCode: "IR" },
  { name: "Bandar Abbas", country: "Iran", countryCode: "IR" },
  { name: "Kerman", country: "Iran", countryCode: "IR" },
  { name: "Yazd", country: "Iran", countryCode: "IR" },
  { name: "Urmia", country: "Iran", countryCode: "IR" },
  { name: "Rasht", country: "Iran", countryCode: "IR" },
  { name: "Sari", country: "Iran", countryCode: "IR" },
  { name: "Gorgan", country: "Iran", countryCode: "IR" },
  { name: "Zahedan", country: "Iran", countryCode: "IR" },
  { name: "Kermanshah", country: "Iran", countryCode: "IR" },
  { name: "Sanandaj", country: "Iran", countryCode: "IR" },
  { name: "Bushehr", country: "Iran", countryCode: "IR" },
  { name: "Abadan", country: "Iran", countryCode: "IR" },
  { name: "Dezful", country: "Iran", countryCode: "IR" },
  { name: "Asaluyeh", country: "Iran", countryCode: "IR" },
  { name: "Chabahar", country: "Iran", countryCode: "IR" },
  { name: "Ardabil", country: "Iran", countryCode: "IR" },
  { name: "Birjand", country: "Iran", countryCode: "IR" },
  { name: "Bojnurd", country: "Iran", countryCode: "IR" },
  { name: "Ilam", country: "Iran", countryCode: "IR" },
  { name: "Shahr-e Kord", country: "Iran", countryCode: "IR" },
  { name: "Semnan", country: "Iran", countryCode: "IR" },
  { name: "Yasuj", country: "Iran", countryCode: "IR" },
  { name: "Zanjan", country: "Iran", countryCode: "IR" },
  { name: "Arak", country: "Iran", countryCode: "IR" },
  { name: "Bandar Lengeh", country: "Iran", countryCode: "IR" },
  { name: "Khorramabad", country: "Iran", countryCode: "IR" },

  // == Cities in Orange County, USA ==
  { name: "Anaheim", country: "USA", countryCode: "US" },
  { name: "Santa Ana", country: "USA", countryCode: "US" },
  { name: "Huntington Beach", country: "USA", countryCode: "US" },
  { name: "Garden Grove", country: "USA", countryCode: "US" },
  { name: "Orange", country: "USA", countryCode: "US" },
  { name: "Fullerton", country: "USA", countryCode: "US" },
  { name: "Costa Mesa", country: "USA", countryCode: "US" },
  { name: "Mission Viejo", country: "USA", countryCode: "US" },
  { name: "Newport Beach", country: "USA", countryCode: "US" },
  { name: "Laguna Niguel", country: "USA", countryCode: "US" },
  { name: "Lake Forest", country: "USA", countryCode: "US" },
  { name: "Tustin", country: "USA", countryCode: "US" },
  { name: "Yorba Linda", country: "USA", countryCode: "US" },
  { name: "San Clemente", country: "USA", countryCode: "US" },
  { name: "Dana Point", country: "USA", countryCode: "US" },
  { name: "Laguna Beach", country: "USA", countryCode: "US" },
  { name: "Aliso Viejo", country: "USA", countryCode: "US" },
  { name: "Brea", country: "USA", countryCode: "US" },
  { name: "Rancho Santa Margarita", country: "USA", countryCode: "US" },

  // == Major Cities in the United Kingdom ==
  // England
  { name: "Birmingham", country: "United Kingdom", countryCode: "GB" },
  { name: "Leeds", country: "United Kingdom", countryCode: "GB" },
  { name: "Sheffield", country: "United Kingdom", countryCode: "GB" },
  { name: "Liverpool", country: "United Kingdom", countryCode: "GB" },
  { name: "Bristol", country: "United Kingdom", countryCode: "GB" },
  { name: "Newcastle upon Tyne", country: "United Kingdom", countryCode: "GB" },
  { name: "Nottingham", country: "United Kingdom", countryCode: "GB" },
  { name: "Southampton", country: "United Kingdom", countryCode: "GB" },
  { name: "Leicester", country: "United Kingdom", countryCode: "GB" },
  { name: "Coventry", country: "United Kingdom", countryCode: "GB" },
  { name: "Cambridge", country: "United Kingdom", countryCode: "GB" },
  { name: "Oxford", country: "United Kingdom", countryCode: "GB" },
  { name: "Brighton", country: "United Kingdom", countryCode: "GB" },
  // Scotland
  { name: "Edinburgh", country: "United Kingdom", countryCode: "GB" },
  { name: "Aberdeen", country: "United Kingdom", countryCode: "GB" },
  { name: "Dundee", country: "United Kingdom", countryCode: "GB" },
  // Wales
  { name: "Cardiff", country: "United Kingdom", countryCode: "GB" },
  { name: "Swansea", country: "United Kingdom", countryCode: "GB" },
  { name: "Newport", country: "United Kingdom", countryCode: "GB" },
  // Northern Ireland
  { name: "Belfast", country: "United Kingdom", countryCode: "GB" },
  { name: "Derry", country: "United Kingdom", countryCode: "GB" },

  // == Capital & Major Cities of Europe ==
  { name: "Athens", country: "Greece", countryCode: "GR" },
  { name: "Barcelona", country: "Spain", countryCode: "ES" },
  { name: "Belgrade", country: "Serbia", countryCode: "RS" },
  { name: "Brussels", country: "Belgium", countryCode: "BE" },
  { name: "Budapest", country: "Hungary", countryCode: "HU" },
  { name: "Dublin", country: "Ireland", countryCode: "IE" },
  { name: "Geneva", country: "Switzerland", countryCode: "CH" },
  { name: "Helsinki", country: "Finland", countryCode: "FI" },
  { name: "Kyiv", country: "Ukraine", countryCode: "UA" },
  { name: "Lisbon", country: "Portugal", countryCode: "PT" },
  { name: "Madrid", country: "Spain", countryCode: "ES" },
  { name: "Milan", country: "Italy", countryCode: "IT" },
  { name: "Moscow", country: "Russia", countryCode: "RU" },
  { name: "Nicosia", country: "Cyprus", countryCode: "CY" },
  { name: "Prague", country: "Czech Republic", countryCode: "CZ" },
  { name: "Rome", country: "Italy", countryCode: "IT" },
  { name: "Warsaw", country: "Poland", countryCode: "PL" },
  { name: "Zurich", country: "Switzerland", countryCode: "CH" },

  // == Capital & Major Cities of Asia ==
  { name: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE" },
  { name: "Amman", country: "Jordan", countryCode: "JO" },
  { name: "Baghdad", country: "Iraq", countryCode: "IQ" },
  { name: "Beijing", country: "China", countryCode: "CN" },
  { name: "Shanghai", country: "China", countryCode: "CN" },
  { name: "Guangzhou", country: "China", countryCode: "CN" },
  { name: "Shenzhen", country: "China", countryCode: "CN" },
  { name: "Beirut", country: "Lebanon", countryCode: "LB" },
  { name: "Doha", country: "Qatar", countryCode: "QA" },
  { name: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
  { name: "Islamabad", country: "Pakistan", countryCode: "PK" },
  { name: "Jakarta", country: "Indonesia", countryCode: "ID" },
  { name: "Kuwait City", country: "Kuwait", countryCode: "KW" },
  { name: "Manama", country: "Bahrain", countryCode: "BH" },
  { name: "Manila", country: "Philippines", countryCode: "PH" },
  { name: "Mumbai", country: "India", countryCode: "IN" },
  { name: "Muscat", country: "Oman", countryCode: "OM" },
  { name: "New Delhi", country: "India", countryCode: "IN" },
  { name: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
  { name: "Seoul", country: "South Korea", countryCode: "KR" },
  { name: "Singapore", country: "Singapore", countryCode: "SG" },
  { name: "Taipei", country: "Taiwan", countryCode: "TW" },
  { name: "Tashkent", country: "Uzbekistan", countryCode: "UZ" },
  { name: "Tokyo", country: "Japan", countryCode: "JP" },

  // == USA Capitals & Major Cities ==
  { name: "Washington, D.C.", country: "USA", countryCode: "US" },
  { name: "New York City", country: "USA", countryCode: "US" },
  { name: "Chicago", country: "USA", countryCode: "US" },
  { name: "Houston", country: "USA", countryCode: "US" },
  { name: "Phoenix", country: "USA", countryCode: "US" },
  { name: "San Diego", country: "USA", countryCode: "US" },
  { name: "Dallas", country: "USA", countryCode: "US" },
  { name: "San Jose", country: "USA", countryCode: "US" },
  { name: "Austin", country: "USA", countryCode: "US" },
  { name: "San Francisco", country: "USA", countryCode: "US" },
  { name: "Boston", country: "USA", countryCode: "US" },
  { name: "Seattle", country: "USA", countryCode: "US" },
  { name: "Denver", country: "USA", countryCode: "US" },
  { name: "Las Vegas", country: "USA", countryCode: "US" },
  { name: "Atlanta", country: "USA", countryCode: "US" },
  { name: "Miami", country: "USA", countryCode: "US" },
  { name: "Sacramento", country: "USA", countryCode: "US" },
  { name: "Albany", country: "USA", countryCode: "US" },
  { name: "Annapolis", country: "USA", countryCode: "US" },
  { name: "Augusta", country: "USA", countryCode: "US" },
  { name: "Baton Rouge", country: "USA", countryCode: "US" },
  { name: "Bismarck", country: "USA", countryCode: "US" },
  { name: "Boise", country: "USA", countryCode: "US" },
  { name: "Carson City", country: "USA", countryCode: "US" },
  { name: "Charleston", country: "USA", countryCode: "US" },
  { name: "Cheyenne", country: "USA", countryCode: "US" },
  { name: "Columbia", country: "USA", countryCode: "US" },
  { name: "Columbus", country: "USA", countryCode: "US" },
  { name: "Concord", country: "USA", countryCode: "US" },
  { name: "Des Moines", country: "USA", countryCode: "US" },
  { name: "Dover", country: "USA", countryCode: "US" },
  { name: "Frankfort", country: "USA", countryCode: "US" },
  { name: "Harrisburg", country: "USA", countryCode: "US" },
  { name: "Hartford", country: "USA", countryCode: "US" },
  { name: "Helena", country: "USA", countryCode: "US" },
  { name: "Honolulu", country: "USA", countryCode: "US" },
  { name: "Indianapolis", country: "USA", countryCode: "US" },
  { name: "Jackson", country: "USA", countryCode: "US" },
  { name: "Jefferson City", country: "USA", countryCode: "US" },
  { name: "Juneau", country: "USA", countryCode: "US" },
  { name: "Lansing", country: "USA", countryCode: "US" },
  { name: "Lincoln", country: "USA", countryCode: "US" },
  { name: "Little Rock", country: "USA", countryCode: "US" },
  { name: "Madison", country: "USA", countryCode: "US" },
  { name: "Montgomery", country: "USA", countryCode: "US" },
  { name: "Montpelier", country: "USA", countryCode: "US" },
  { name: "Nashville", country: "USA", countryCode: "US" },
  { name: "Oklahoma City", country: "USA", countryCode: "US" },
  { name: "Olympia", country: "USA", countryCode: "US" },
  { name: "Pierre", country: "USA", countryCode: "US" },
  { name: "Providence", country: "USA", countryCode: "US" },
  { name: "Raleigh", country: "USA", countryCode: "US" },
  { name: "Richmond", country: "USA", countryCode: "US" },
  { name: "Saint Paul", country: "USA", countryCode: "US" },
  { name: "Salem", country: "USA", countryCode: "US" },
  { name: "Salt Lake City", country: "USA", countryCode: "US" },
  { name: "Santa Fe", country: "USA", countryCode: "US" },
  { name: "Springfield", country: "USA", countryCode: "US" },
  { name: "Tallahassee", country: "USA", countryCode: "US" },
  { name: "Topeka", country: "USA", countryCode: "US" },
  { name: "Trenton", country: "USA", countryCode: "US" },
];

